Ajuste de README.md y ajuste workflows para que ignore el README

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -18,6 +18,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Check if README.md changed
+        run: |
+          if git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep -q 'README\.md'; then
+            echo "README.md changed. Skipping the workflow."
+            exit 78 # Exit code 78 skips the workflow
+          fi
+
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
